config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }

  namespace :user do
    get 'dashboard' => 'dashboard#index'
    namespace :dashboard do
      resource :pets
    end
  end

  get 'pets/find' => 'pets#find'

  resources :pets, param: :chip_number

  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'static_pages'

  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.haml
.ui.inverted.vertical.center.aligned.segment
  .ui.container.fluid
    .ui.huge.borderless.menu.inverted.header
      .ui.container
        = link_to root_path, class: 'item header' do
          PetNotary
        .right.menu
        - if user_signed_in?
          = link_to pets_find_path do
            .ui.inverted.button.green Find an owner
          = link_to pets_path do
            .ui.inverted.button.violet Your pets
          = link_to edit_user_registration_path do
            .ui.inverted.button Settings
          = link_to destroy_user_session_path, method: :delete do
            .ui.inverted.button.red Sign out
        - else
          = link_to pets_find_path do
            .ui.item.inverted.button.green Find an owner
          = link_to new_user_session_path do
            .ui.item.inverted.button.blue Login
  .ui.text.container
    %h1.ui.inverted.header
      PetNotary
    %h2
      Pakistan's
      %strong only public
      pet microchip database
    = form_tag(new_registration_path(:user), method: :get, class: 'ui action input') do
      = text_field_tag(:chip_number, nil, {placeholder: 'Chip Number', class: 'ui'})
      = button_tag(:register, class: 'ui huge primary button') do
        Register
        %i.right.arrow.icon
  .ui.container.top.space
    .ui.three.column.stackable.grid.centered
      .ui.column.center.aligned
        .ui.segment.inverted.violet.facts
          .ui.h2.header What is a microchip implant for pets?
          A microchip is a implant is a small — the size of a rice grain — permanent electronic identification device that's injected just under the skin behind your pet's neck.
      .ui.column.center.aligned
        .ui.segment.inverted.violet.facts
          .ui.h2.header Is it safe? Where can I get it?
          Yes! The chip itself is encased in sterile glass, and the procedure is as quick and painless as an injection. For more information, talk to your existing vet!
      .ui.column.center.aligned
        .ui.segment.inverted.violet.facts
          .ui.h2.header How does registration work?
          Each microchip has a unique ID that can be registered to your name here at PetList, permantly linking you to your pet. Lost pets can be reunited with their owners here.
.ui.inverted.vertical.footer.segment
  .ui.container
    .ui.stackable.inverted.divided.equal.height.stackable.grid
      .three.wide.column
        %h4.ui.inverted.header Terms
        %p By registering on PetList you grant Amin Shah Gilani a perpetual, irrevocable right
        to serve enquirers your registered data. Enquirers can query your data using

      .three.wide.column
        %h4.ui.inverted.header Contact
        .ui.inverted.link.list
          %a.item{:href => "mailto:feedback.petnotary@gilani.me"}
            %i.envelope.outline.icon
            Feedback
          %a.item{:href => "mailto:partnerships.petnotary@gilani.me"}
            %i.envelope.outline.icon
            Partnerships
          %a.item{:href => "mailto:dataedit.petnotary@gilani.me"}
            %i.envelope.outline.icon
            Data Modification
          %a.item{:href => "mailto:support.petnotary@gilani.me"}
            %i.envelope.outline.icon
            Support
      .seven.wide.column
        %h4.ui.inverted.header About
        %p
          Hi, I created PetList because after my dog was micro-chipped, I realized I had nowhere to register him. Realizing that I was one of a handful of people skilled enough to create PetList, I did.
        %p
          PetList is free to register and use for now. In the future I might charge a modest one-time registration fee to cover server costs. However, once registered, you're registered forever.
.ui.inverted.vertical.footer.segment.center.aligned
  %i.code.icon
  in
  %strong LHR
  by
  %strong
    %a{href: 'https://gilani.me'}Amin Shah Gilani