config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }

  namespace :user do
    get 'dashboard' => 'dashboard#index'
    namespace :dashboard do
      resource :pets
    end
  end

  get 'pets/find' => 'pets#find'

  resources :pets, param: :chip_number

  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
# == Schema Information
#
# Table name: pets
#
#  id               :bigint(8)        not null, primary key
#  chip_number      :string           not null
#  mixed_breed      :boolean          default(TRUE)
#  name             :string
#  primary_breed    :string
#  primary_color    :string
#  privacy_settings :integer          default(0)
#  secondary_breed  :string
#  secondary_color  :string
#  species          :integer          not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :bigint(8)
#
# Indexes
#
#  index_pets_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Pet < ApplicationRecord
  validates :species, presence: true
  validates :chip_number, presence: true

  # Animal data
  animal_data_file = Rails.root.join('vendor', 'lib', 'animal_data.yaml')
  ANIMAL_DATA = YAML::load_file(animal_data_file).symbolize_keys

  ANIMAL_SPECIES = ANIMAL_DATA[:ANIMAL_SPECIES]
  DOG_BREEDS     = ANIMAL_DATA[:DOG_BREEDS]
  DOG_COLORS     = ANIMAL_DATA[:DOG_COLORS]
  CAT_BREEDS     = ANIMAL_DATA[:CAT_BREEDS]
  CAT_COLORS     = ANIMAL_DATA[:CAT_COLORS]


  belongs_to :user

  def to_param
    chip_number
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show]

  # GET /pets
  # GET /pets.json
  def index
  end

  def find
    #code
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find_by(chip_number: params[:chip_number])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(
        :chip_number,
        :animal_type,
        :animal_name,
        :owner_name,
        :owner_email,
        :owner_email_confirmation,
        :owner_phone)
    end
end

app/controllers/user/dashboard/pets_controller.rb
class User::Dashboard::PetsController < ApplicationController
  before_action :set_pet, only: [:show]

  # GET /pets
  # GET /pets.json
  def index
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find_by(chip_number: params[:chip_number])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(
        :chip_number,
        :animal_type,
        :animal_name,
        :owner_name,
        :owner_email,
        :owner_email_confirmation,
        :owner_phone
      )
    end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < ApplicationController
  before_action :set_dashboard, only: [:show]

  def index
  end

  private
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/user/dashboard/pets/_form.html.haml
= form_for @pet do |f|
  - if @pet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pet.errors.count, "error")} prohibited this pet from being saved:"
      %ul
        - @pet.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :chip_number
    = f.text_field :chip_number
  .field
    = f.label :animal_type
    = f.text_field :animal_type
  .field
    = f.label :animal_name
    = f.text_field :animal_name
  .field
    = f.label :owner_name
    = f.text_field :owner_name
  .field
    = f.label :owner_email
    = f.text_field :owner_email
  .field
    = f.label :owner_email_confirmation
    = f.text_field :owner_email_confirmation
  .field
    = f.label :owner_password
    = f.text_field :owner_password
  .field
    = f.label :owner_password_confirmation
    = f.text_field :owner_password_confirmation
  .field
    = f.label :owner_phone
    = f.text_field :owner_phone
  .actions
    = f.submit 'Save'

app/views/user/dashboard/pets/edit.html.haml
%h1 Editing pet

= render 'form'

= link_to 'Show', @pet
\|
= link_to 'Back', pets_path

app/views/user/dashboard/pets/find.html.haml
= javascript_pack_tag 'find_pet'
:css
  .hidden.menu {
    display: none;
  }

  .facts {
   min-height: 145px;
  }

  .top.space {
   margin-top: 1.5em;
  }

  .masthead.segment {
    min-height: 700px;
    padding: 1em 0em;
  }
  .masthead .logo.item img {
    margin-right: 1em;
  }
  .masthead .ui.menu .ui.button {
    margin-left: 0.5em;
  }
  .masthead h1.ui.header {
    margin-top: 3em;
    margin-bottom: 0em;
    font-size: 4em;
    font-weight: normal;
  }
  .masthead h2 {
    font-size: 1.7em;
    font-weight: normal;
  }

  .ui.vertical.stripe {
    padding: 8em 0em;
  }
  .ui.vertical.stripe h3 {
    font-size: 2em;
  }
  .ui.vertical.stripe .button + h3,
  .ui.vertical.stripe p + h3 {
    margin-top: 3em;
  }
  .ui.vertical.stripe .floated.image {
    clear: both;
  }
  .ui.vertical.stripe p {
    font-size: 1.33em;
  }
  .ui.vertical.stripe .horizontal.divider {
    margin: 3em 0em;
  }

  .quote.stripe.segment {
    padding: 0em;
  }
  .quote.stripe.segment .grid .column {
    padding-top: 5em;
    padding-bottom: 5em;
  }

  .footer.segment {
    padding: 5em 0em;
  }

  .secondary.pointing.menu .toc.item {
    display: none;
  }

  @media only screen and (max-width: 700px) {
    .ui.fixed.menu {
      display: none !important;
    }
    .secondary.pointing.menu .item,
    .secondary.pointing.menu .menu {
      display: none;
    }
    .secondary.pointing.menu .toc.item {
      display: block;
    }
    .masthead.segment {
      min-height: 350px;
    }
    .masthead h1.ui.header {
      font-size: 2em;
      margin-top: 1.5em;
    }
    .masthead h2 {
      margin-top: 0.5em;
      font-size: 1.5em;
    }
  }
:javascript
  $(document)
    .ready(function() {

      // fix menu when passed
      $('.masthead')
        .visibility({
          once: false,
          onBottomPassed: function() {
            $('.fixed.menu').transition('fade in');
          },
          onBottomPassedReverse: function() {
            $('.fixed.menu').transition('fade out');
          }
        })
      ;

      // create sidebar and attach to menu open
      $('.ui.sidebar')
        .sidebar('attach events', '.toc.item')
      ;

    })
  ;
%body
.ui.vertical.masthead.center.aligned.segment
  .ui.container
    .ui.large.secondary.pointing.menu
      %a.toc.item
        %i.sidebar.icon
      %a.active.item{href: root_path} Home
      .right.item
        %a.ui.inverted.button.green{href: root_path} Register a Pet
        %a.ui.inverted.button.blue{href: new_user_session_path} Login
  .ui.text.container
    %h1.ui.header
      Find an owner
    %h3
      Help reunite a pet with their family using
      Pakistan's
      %strong only public
      pet microchip database
    #find-pet-form-wrapper

  .ui.container.top.space
    .ui.three.column.stackable.grid.centered
      .ui.column.center.aligned
        .ui.segment.inverted.violet.facts
          .ui.h2.header What is a microchip implant for pets?
          A microchip is a implant is a small — the size of a rice grain — permanent electronic identification device that's injected just under the skin behind your pet's neck.
      .ui.column.center.aligned
        .ui.segment.inverted.violet.facts
          .ui.h2.header Is it safe? Where can I get it?
          Yes! The chip itself is encased in sterile glass, and the procedure is as quick and painless as an injection. For more information, talk to your existing vet!
      .ui.column.center.aligned
        .ui.segment.inverted.violet.facts
          .ui.h2.header How does registration work?
          Each microchip has a unique ID that can be registered to your name here at PetList, permantly linking you to your pet. Lost pets can be reunited with their owners here.
.ui.inverted.vertical.footer.segment
  .ui.container
    .ui.stackable.inverted.divided.equal.height.stackable.grid
      .three.wide.column
        %h4.ui.inverted.header Terms
        %p By registering on PetList you grant Amin Shah Gilani a perpetual, irrevocable right
        to serve enquirers your registered data. Enquirers can query your data using

      .three.wide.column
        %h4.ui.inverted.header Contact
        .ui.inverted.link.list
          %a.item{:href => "mailto:feedback.petnotary@gilani.me"}
            %i.envelope.outline.icon
            Feedback
          %a.item{:href => "mailto:partnerships.petnotary@gilani.me"}
            %i.envelope.outline.icon
            Partnerships
          %a.item{:href => "mailto:dataedit.petnotary@gilani.me"}
            %i.envelope.outline.icon
            Data Modification
          %a.item{:href => "mailto:support.petnotary@gilani.me"}
            %i.envelope.outline.icon
            Support
      .seven.wide.column
        %h4.ui.inverted.header About
        %p
          Hi, I created PetList because after my dog was micro-chipped, I realized I had nowhere to register him. Realizing that I was one of a handful of people skilled enough to create PetList, I did.
        %p
          PetList is free to register and use for now. In the future I might charge a modest one-time registration fee to cover server costs. However, once registered, you're registered forever.
.ui.inverted.vertical.footer.segment.center.aligned
  %i.code.icon
  in
  %strong LHR
  by
  %strong
    %a{href: 'https://gilani.me'}Amin Shah Gilani

app/views/user/dashboard/pets/index.html.haml
%h1 Find a pet

#find-pet-form-wrapper

= link_to 'New Pet', new_pet_path

= javascript_pack_tag 'find_pet'

app/views/user/dashboard/pets/new.html.haml
%h1 New pet

= render 'form'

= link_to 'Back', pets_path

app/views/user/dashboard/pets/show.html.haml
:css
  .hidden.menu {
    display: none;
  }

  .facts {
   min-height: 145px;
  }

  .top.space {
   margin-top: 1.5em;
  }

  .masthead.segment {
    min-height: 700px;
    padding: 1em 0em;
  }
  .masthead .logo.item img {
    margin-right: 1em;
  }
  .masthead .ui.menu .ui.button {
    margin-left: 0.5em;
  }
  .masthead h1.ui.header {
    margin-top: 3em;
    margin-bottom: 0em;
    font-size: 4em;
    font-weight: normal;
  }
  .masthead h2 {
    font-size: 1.7em;
    font-weight: normal;
  }

  .ui.vertical.stripe {
    padding: 8em 0em;
  }
  .ui.vertical.stripe h3 {
    font-size: 2em;
  }
  .ui.vertical.stripe .button + h3,
  .ui.vertical.stripe p + h3 {
    margin-top: 3em;
  }
  .ui.vertical.stripe .floated.image {
    clear: both;
  }
  .ui.vertical.stripe p {
    font-size: 1.33em;
  }
  .ui.vertical.stripe .horizontal.divider {
    margin: 3em 0em;
  }

  .quote.stripe.segment {
    padding: 0em;
  }
  .quote.stripe.segment .grid .column {
    padding-top: 5em;
    padding-bottom: 5em;
  }

  .footer.segment {
    padding: 5em 0em;
  }

  .secondary.pointing.menu .toc.item {
    display: none;
  }

  @media only screen and (max-width: 700px) {
    .ui.fixed.menu {
      display: none !important;
    }
    .secondary.pointing.menu .item,
    .secondary.pointing.menu .menu {
      display: none;
    }
    .secondary.pointing.menu .toc.item {
      display: block;
    }
    .masthead.segment {
      min-height: 350px;
    }
    .masthead h1.ui.header {
      font-size: 2em;
      margin-top: 1.5em;
    }
    .masthead h2 {
      margin-top: 0.5em;
      font-size: 1.5em;
    }
  }
.ui.inverted.vertical.masthead.center.aligned.segment
  .ui.container
    .ui.large.secondary.inverted.pointing.menu
      %a.active.item Home
      .right.item
        %a.ui.inverted.button.green{href: pets_find_path} Find an Owner
        %a.ui.inverted.button{href: new_user_session_path} Login

  .ui.text.container
    %h1 We Found Someone!
    .ui.segment.inverted.blue
      %h2.ui.header
        Pet Information
      %p
        %b Chip number:
        = @pet.chip_number
      %p
        %b Species:
        = @pet.species
      %p
        %b Name:
        = @pet.name
    .ui.segment.inverted.green
      %h2.ui.header
        Owner Information
      %p
        %b Name:
        = @pet.user.name
      %p
        %b Email:
        = @pet.user.email
      %p
        %b Primary Phone:
        = @pet.user.phone_primary
      %p
        %b Secondary Phone:
        = @pet.user.phone_secondary
      %p
        %b Postal Code:
        = @pet.user.postal_code
      %p
        %b Province:
        = @pet.user.province
      %p
        %b Address:
        = @pet.user.address
      %p
        %b City:
        = @pet.user.city
      %p
        %b Country:
        = @pet.user.country

  .ui.inverted.vertical.footer.segment
    .ui.container
      .ui.stackable.inverted.divided.equal.height.stackable.grid
        .three.wide.column
          %h4.ui.inverted.header Terms
          %p By registering on PetList you grant Amin Shah Gilani a perpetual, irrevocable right
          to serve enquirers your registered data. Enquirers can query your data using

        .three.wide.column
          %h4.ui.inverted.header Contact
          .ui.inverted.link.list
            %a.item{:href => "mailto:feedback.petnotary@gilani.me"}
              %i.envelope.outline.icon
              Feedback
            %a.item{:href => "mailto:partnerships.petnotary@gilani.me"}
              %i.envelope.outline.icon
              Partnerships
            %a.item{:href => "mailto:dataedit.petnotary@gilani.me"}
              %i.envelope.outline.icon
              Data Modification
            %a.item{:href => "mailto:support.petnotary@gilani.me"}
              %i.envelope.outline.icon
              Support
        .seven.wide.column
          %h4.ui.inverted.header About
          %p
            Hi, I created PetList because after my dog was micro-chipped, I realized I had nowhere to register him. Realizing that I was one of a handful of people skilled enough to create PetList, I did.
          %p
            PetList is free to register and use for now. In the future I might charge a modest one-time registration fee to cover server costs. However, once registered, you're registered forever.
  .ui.inverted.vertical.footer.segment.center.aligned
    %i.code.icon
    in
    %strong LHR
    by
    %strong
      %a{href: 'https://gilani.me'}Amin Shah Gilani